language: node_js
node_js: "node"

# OS
dist: xenial

# install dependencies
install:
  - npm install

# install database
services:
  - postgresql

# setup database
before_script:
  - psql -c "CREATE ROLE $PG_USER PASSWORD '$PG_PASSWORD' LOGIN"
  - createdb -O $PG_USER $PG_USER
  - psql -d $PG_USER -c 'CREATE EXTENSION IF NOT EXISTS "pgcrypto"'
  - PGPASSWORD=$PG_PASSWORD psql -U $PG_USER -d $PG_USER -f ./db/setup.sql

# run unit tests
script:
- sudo env "PATH=$PATH" npm run test
